AllCops:
  TargetRubyVersion: 2.1

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/LambdaCall:
  EnforcedStyle: braces
